.PHONY: clean

all: edu/kit/informatik/MyParser.class
	java edu.kit.informatik.MyParser

edu/kit/informatik/MyParser.class:
	javac edu/kit/informatik/MyParser.java


solution: edu/kit/informatik/MyParserSolution.class
	java edu.kit.informatik.MyParserSolution

edu/kit/informatik/MyParserSolution.class:
	javac edu/kit/informatik/MyParserSolution.java

clean:
	rm -f edu/kit/informatik/*.class
